<?php

/** Register Buildystrap Options Page **/
function register_buildy_acf_options_page()
{
  if (function_exists('acf_add_options_page')) {
    acf_add_options_page([
      'page_title' => __('Buildystrap Settings'),
      'menu_title' => __('Settings'),
      'menu_slug' => 'buildystrap-settings',
      'parent_slug' => 'buildystrap',
    ]);
  }
}

add_action('acf/init', 'register_buildy_acf_options_page');

/** Place ACF PHP export below **/


if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group([
    'key' => 'group_62ce4dc3dd60d',
    'title' => 'Buildystrap Settings',
    'fields' => [
      [
        'key' => 'field_62ce53951cb9f',
        'label' => 'Company Details',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62eb436da1053',
        'label' => 'Company Details',
        'name' => 'buildystrap_company_details',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,

        'layout' => 'row',
        'sub_fields' => [
          [
            'key' => 'field_62ce4dd4597b0',
            'label' => 'Site Logo',
            'name' => 'site_logo',
            'type' => 'image',
            'required' => 0,
            'conditional_logic' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
          ],
          [
            'key' => 'field_62ce52d21cb95',
            'label' => 'Company Phone',
            'name' => 'company_phone',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
          ],
          [
            'key' => 'field_company_phone_alt',
            'label' => 'Company Phone 2',
            'name' => 'company_phone_alt',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
          ],
          [
            'key' => 'field_62ce52e31cb96',
            'label' => 'Company Fax',
            'name' => 'company_fax',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
          ],
          [
            'key' => 'field_62ce52ea1cb97',
            'label' => 'Company Email',
            'name' => 'company_email',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
          ],
          [
            'key' => 'field_62ce52f51cb98',
            'label' => 'Company Address',
            'name' => 'company_address',
            'type' => 'textarea',
            'required' => 0,
            'conditional_logic' => 0,
            'rows' => 2,
            'new_lines' => 'br',
          ],
          [
            'key' => 'field_62ce53041cb99',
            'label' => 'Company ABN',
            'name' => 'company_abn',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
          ],
          [
            'key' => 'field_62ce530f1cb9a',
            'label' => 'Social Links',
            'name' => 'social_links',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62ce531c1cb9b',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',                
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62fd80aa001f5',
                'label' => 'Icon Style',
                'name' => 'icon_style',
                'type' => 'select',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
                'choices' => [
                  'fa' => 'Font Awesome',
                  'la' => 'Line Awesome',
                ],
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
              ],
              [
                'key' => 'field_62ce53271cb9c',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62ce53561cb9d',
                'label' => 'URL',
                'name' => 'url',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
          [
            'key' => 'field_62ce53851cb9e',
            'label' => 'Google API Key',
            'name' => 'google_api_key',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
          ],
        ],
      ],
      [
        'key' => 'field_62ce53ad1cba0',
        'label' => 'Sitewide Message',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62ce544744eff',
        'label' => 'Sitewide Message',
        'name' => 'buildystrap_sitewide_message',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'row',
        'sub_fields' => [
          [
            'key' => 'field_62ce53fb44efe',
            'label' => 'Enable Sitewide Message',
            'name' => 'enable_sitewide_message',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [],
            'default_value' => 0,
            'ui' => 1,
          ],
          [
            'key' => 'field_62ce555444f01',
            'label' => 'Content',
            'name' => 'content',
            'type' => 'wysiwyg',
            'required' => 0,
            'conditional_logic' => 0,
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ],
          [
            'key' => 'field_62ce556144f02',
            'label' => 'BG Colour',
            'name' => 'bg_colour',
            'type' => 'select',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '50',
            ],
            'choices' => [],            
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'label',
            'ajax' => 0,
          ],
          [
            'key' => 'field_62ce558644f03',
            'label' => 'Text Colour',
            'name' => 'text_colour',
            'type' => 'select',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '50',
            ],
            'choices' => [],
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'label',
            'ajax' => 0,
          ],
        ],
      ],
      [
        'key' => 'field_62ce566b8da7c',
        'label' => 'Theme Colours',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62ce56808da7d',
        'label' => 'Theme Colours',
        'name' => 'buildystrap_theme_colours',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'block',
        'sub_fields' => [
          [
            'key' => 'field_62ce578d8da87',            
            'label' => 'Additional Colours',
            'name' => 'additional_colours',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62ce57a68da88',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],              [
                'key' => 'field_62ce57ab8da89',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
            ],
          ],
          [
            'key' => 'field_62ce5cbe77fbf',
            'label' => 'Text Colour Headings',
            'name' => 'text_colour_headings',
            'type' => 'select',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
            'choices' => [
              'None' => 'None',
              '#25d03a' => 'primary',
              '#2a2a2a' => 'secondary',
              '#dd3333' => 'tertiary',
              '#198754' => 'success',
              '#dc3545' => 'danger',
              '#ffc107' => 'warning',
              '#0dcaf0' => 'info',
              '#ececec' => 'light',
              '#3f3f3f' => 'dark',
              '' => '900',
              '#0a0a0a' => 'black',
            ],
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'array',
            'ajax' => 0,
          ],
          [
            'key' => 'field_62ce5cd577fc0',
            'label' => 'Text Colour Body',
            'name' => 'text_colour_body',
            'type' => 'select',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
            'choices' => [
              'None' => 'None',
              '#25d03a' => 'primary',
              '#2a2a2a' => 'secondary',
              '#dd3333' => 'tertiary',
              '#198754' => 'success',
              '#dc3545' => 'danger',
              '#ffc107' => 'warning',
              '#0dcaf0' => 'info',
              '#ececec' => 'light',
              '#3f3f3f' => 'dark',
              '' => '900',
              '#0a0a0a' => 'black',
            ],
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'array',
            'ajax' => 0,
          ],
          [
            'key' => 'field_62ce5d0577fc1',
            'label' => 'Link Colour',
            'name' => 'link_colour',
            'type' => 'select',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '33',
            ],
            'choices' => [
              'None' => 'None',
              '#25d03a' => 'primary',
              '#2a2a2a' => 'secondary',
              '#dd3333' => 'tertiary',
              '#198754' => 'success',
              '#dc3545' => 'danger',
              '#ffc107' => 'warning',
              '#0dcaf0' => 'info',
              '#ececec' => 'light',
              '#3f3f3f' => 'dark',
              '' => '900',
              '#0a0a0a' => 'black',
            ],
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'label',
            'ajax' => 0,
          ],
          [
            'key' => 'field_62eb495fab606',
            'label' => 'Included Colours',
            'name' => 'included',
            'type' => 'group',
            'required' => 0,
            'conditional_logic' => 0,

            'layout' => 'block',
            'sub_fields' => [
              [
                'key' => 'field_62ce56878da7e',
                'label' => 'Primary',
                'name' => 'primary',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce56cb8da7f',
                'label' => 'Secondary',
                'name' => 'secondary',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce5b8bd12aa',
                'label' => 'Tertiary',
                'name' => 'tertiary',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce56d38da80',
                'label' => 'Success',
                'name' => 'success',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#198754',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce574a8da81',
                'label' => 'Danger',
                'name' => 'danger',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#dc3545',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce57578da82',
                'label' => 'Warning',
                'name' => 'warning',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#ffc107',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce57628da83',
                'label' => 'Info',
                'name' => 'info',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#0dcaf0',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce57698da84',
                'label' => 'Light',
                'name' => 'light',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#f8f9fa',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
              [
                'key' => 'field_62ce576f8da85',
                'label' => 'Dark',
                'name' => 'dark',
                'type' => 'color_picker',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                  'width' => '20',
                ],
                'default_value' => '#212529',
                'enable_opacity' => 0,
                'return_format' => 'string',
              ],
            ],
          ],
        ],
      ],
      [
        'key' => 'field_62ce5d9577fc2',
        'label' => 'Header',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62eb4324a1043',
        'label' => 'Header',
        'name' => 'buildystrap_header',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'block',
        'sub_fields' => [
          [
            'key' => 'field_62ce5d9f77fc3',
            'label' => 'Always show mobile nav?',
            'name' => 'always_show_mobile_nav',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [],
            'default_value' => 0,
            'ui' => 1,
          ],
          [
            'key' => 'field_62eb52287454c',
            'label' => 'Header background colour',
            'name' => 'background_colour',
            'type' => 'select',
            'required' => 0,
            'choices' => [
              'None' => 'None',
              'primary' => '<div style=\'display: flex;\'><span style=\'background: #25d03a; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>primary</div>',
              'secondary' => '<div style=\'display: flex;\'><span style=\'background: #2a2a2a; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>secondary</div>',
              'tertiary' => '<div style=\'display: flex;\'><span style=\'background: #dd3333; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>tertiary</div>',
              'success' => '<div style=\'display: flex;\'><span style=\'background: #198754; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>success</div>',
              'danger' => '<div style=\'display: flex;\'><span style=\'background: #dc3545; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>danger</div>',
              'warning' => '<div style=\'display: flex;\'><span style=\'background: #ffc107; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>warning</div>',
              'info' => '<div style=\'display: flex;\'><span style=\'background: #0dcaf0; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>info</div>',
              'light' => '<div style=\'display: flex;\'><span style=\'background: #ececec; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>light</div>',
              'dark' => '<div style=\'display: flex;\'><span style=\'background: #3f3f3f; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>dark</div>',
              700 => '<div style=\'display: flex;\'><span style=\'background: ; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>700</div>',
              800 => '<div style=\'display: flex;\'><span style=\'background: ; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>800</div>',
              900 => '<div style=\'display: flex;\'><span style=\'background: ; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>900</div>',
              'black' => '<div style=\'display: flex;\'><span style=\'background: #0a0a0a; width: 20px;
						margin-right: 0.6rem; display: block; border-radius: 50%;\'></span>black</div>',
            ],
            'default_value' => false,
            'allow_null' => 0,            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
          ],
        ],
      ],
      [
        'key' => 'field_62ce5db477fc4',
        'label' => 'Structure',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62ce5dc177fc5',
        'label' => 'Structure',
        'name' => 'buildystrap_structure',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'block',
        'sub_fields' => [
          [
            'key' => 'field_61ez60dad795_5',
            'label' => 'Enqueue Bootstrap Bundle',
            'name' => 'use_bootstrap_bundle',
            'type' => 'true_false',
            'instructions' => 'Whether to load custom css or the full bootstrap bundle',
            'required' => 0,
            'conditional_logic' => 0,

            'allow_null' => 0,
            'default_value' => 0,
            'ui' => 1,


          ],
          [
            'key' => 'field_62e202dad6868',
            'label' => 'Default Grid System',
            'name' => 'default_grid_system',
            'type' => 'button_group',
            'instructions' => 'Whether to use flex or grid for the main layout grid system (bootstrap supports both)',
            'required' => 0,
            'conditional_logic' => 0,
            'choices' => [
              'flex' => 'Flex',
              'grid' => 'Grid',
            ],
            'allow_null' => 0,

            'layout' => 'horizontal',
            'return_format' => 'value',
          ],
          [
            'key' => 'field_62ce5e610c56787d',
            'label' => 'Row Gap',
            'name' => 'row_gap',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,

            'default_value' => '3rem',
          ],
          [
            'key' => 'field_62ce5e610c42d',
            'label' => 'Column Gap',
            'name' => 'column_gap',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '3rem',
          ],
          [
            'key' => 'field_62eb1e47bcf2e',
            'label' => 'Module Gap',            'name' => 'module_gap',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,

            'default_value' => '3rem',
          ],
          [
            'key' => 'field_62eb1e2dbcf2c',
            'label' => 'Section Padding',
            'name' => 'section_padding',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
          ],
          [
            'key' => 'field_62eb1e3abcf2d',
            'label' => 'Row Padding',
            'name' => 'row_padding',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '3rem',
          ],
          [
            'key' => 'field_62ce5f850c42e',
            'label' => 'Box Model Sizing',
            'name' => 'box_model_sizing',
            'type' => 'repeater',
            'instructions' => 'Additional settings for margins, paddings and position attributes. Note: These settings are not designed to replace module styles. Any sections / rows / columns / modules that use these settings will retain their existing value if these values are updated.',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62cfcfd3dac94',                
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62ce9fe52661b',                
                'label' => 'Value',
                'name' => 'value',
                'type' => 'text',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],          [
            'key' => 'field_62ceaad3e7135',
            'label' => 'Width',
            'name' => 'width',
            'type' => 'repeater',
            'instructions' => 'Additional settings for width, min-width and max-width attributes. Note: These settings are not designed to replace module styles. Any sections / rows / columns / modules that use these settings will retain their existing value if these values are updated.',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62cfcfe7dac95',
                'label' => 'Label',
                'name' => 'label',                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62ceaad3e7136',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'text',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
          [
            'key' => 'field_62ceaaeae7137',
            'label' => 'Height',
            'name' => 'height',
            'type' => 'repeater',
            'instructions' => 'Additional settings for height, min-height and max-height attributes. Note: These settings are not designed to replace module styles. Any sections / rows / columns / modules that use these settings will retain their existing value if these values are updated.',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62cfcff2dac96',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62ceaaeae7138',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'text',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
        ],
      ],
      [
        'key' => 'field_62eb4286a1026',
        'label' => 'Typography',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62eb4296a1027',
        'label' => 'Typography',
        'name' => 'buildystrap_typography',
        'type' => 'group',
        'instructions' => 'Fonts should be added under _typography.scss and uploaded to /dist/fonts/',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'block',
        'sub_fields' => [
          [
            'key' => 'field_enable_font_awesome',
            'label' => 'Enable Font Awesome 6',
            'name' => 'enable_font_awesome',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
              'width' => '20%',
            ],

            'default_value' => 0,
            'ui' => 1,
          ],
          [
            'key' => 'field_enable_line_awesome',
            'label' => 'Enable Line Awesome',
            'name' => 'enable_line_awesome',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => 0,            
            'wrapper' => [
              'width' => '20%',
            ],
            'default_value' => 0,
            'ui' => 1,
          ],
          [
            'key' => 'field_62eb4296a1037',
            'label' => 'Body Font',
            'name' => 'body_font',
            'type' => 'group',            
            'instructions' => 'Enter the font name exactly as it is in CSS (including spaces / casing if applicable)',
            'required' => 0,
            'conditional_logic' => 0,
            'layout' => 'row',
            'sub_fields' => [
              [
                'key' => 'field_62eb4296a1039',
                'label' => 'Font Name',
                'name' => 'value',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
          [
            'key' => 'field_62eb4296a103a',
            'label' => 'Heading Font',
            'name' => 'heading_font',
            'type' => 'group',
            'instructions' => 'Enter the font name exactly as it is in CSS (including spaces / casing if applicable)',
            'required' => 0,
            'conditional_logic' => 0,
            'layout' => 'row',
            'sub_fields' => [
              [
                'key' => 'field_62eb4296a103c',
                'label' => 'Font Name',
                'name' => 'value',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
          [
            'key' => 'field_62eb4296a103d',
            'label' => 'Additional Fonts',
            'name' => 'additional_fonts',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'sub_fields' => [
              [
                'key' => 'field_62f4718c46e4d',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62eb4296a103f',
                'label' => 'Font Name',
                'name' => 'value',
                'type' => 'text',
                'instructions' => 'Enter the font name exactly as it is in CSS (including spaces / casing if applicable)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
          [
            'key' => 'field_62eb4296a1040',
            'label' => 'Font Size',
            'name' => 'font_size',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_62eb4296a1041',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_62eb4296a1042',
                'label' => 'Size',
                'name' => 'value',
                'type' => 'text',
                'required' => 0,                
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
        ],
      ],
      [
        'key' => 'field_62ce6402e3bb5',
        'label' => 'Module Styles',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'placement' => 'top',
        'endpoint' => 0,
      ],
      [
        'key' => 'field_62ce640fe3bb6',
        'label' => 'Module Styles',
        'name' => 'buildystrap_module_styles',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'layout' => 'block',
        'sub_fields' => [
          [
            'key' => 'field_6310062e71d34',
            'label' => 'Modules',
            'name' => 'modules',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'sub_fields' => [
              [
                'key' => 'field_6310076d94f01',
                'label' => 'Module Name',
                'name' => 'module_name',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_6310065771d35',
                'label' => 'Styles',
                'name' => 'styles',
                'type' => 'repeater',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'sub_fields' => [
                  [
                    'key' => 'field_6310066671d36',
                    'label' => 'Label',
                    'name' => 'label',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [],
                  ],
                  [
                    'key' => 'field_6310066c71d37',
                    'label' => 'Value',
                    'name' => 'value',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [],
                  ],
                ],
              ],
            ],
          ],
          [
            'key' => 'field_631006b771d38',
            'label' => 'Shared',
            'name' => 'shared',
            'type' => 'repeater',
            'required' => 0,
            'conditional_logic' => 0,
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'sub_fields' => [
              [
                'key' => 'field_631006c271d39',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
              [
                'key' => 'field_631006c871d3a',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'text',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [],
              ],
            ],
          ],
        ],
      ],

      /* SCRIPTS TAB */
      array(
        'key' => 'field_scripts_328t4923',
        'label' => 'Code Snippets',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_header_ccript_143b6634',
        'label' => 'Header Snippets',
        'name' => 'buildystrap_header_snippets',
        'type' => 'textarea',
        'required' => 0,
        'instructions' => 'These snippets will be added right before the closing head tag.',
        'conditional_logic' => 0,
        'wrapper' => array(),
        'default_value' => '',
        'placeholder' => '<script>...</script> or <style>...</style>',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_body_ccript_143b6635',
        'label' => 'Body Snippets',
        'name' => 'buildystrap_body_snippets',
        'type' => 'textarea',
        'required' => 0,
        'instructions' => 'These snippets will be added right after the opening body tag.',
        'conditional_logic' => 0,
        'wrapper' => array(),
        'default_value' => '',
        'placeholder' => '<script>...</script> or <style>...</style>',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_footer_ccript_143b6636',
        'label' => 'Footer Snippets',
        'name' => 'buildystrap_footer_snippets',
        'type' => 'textarea',
        'required' => 0,
        'instructions' => 'These snippets will be added right before the closing body tag.',
        'conditional_logic' => 0,
        'wrapper' => array(),
        'default_value' => '',
        'placeholder' => '<script>...</script> or <style>...</style>',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      /* END SCRIPTS TAB */

      /* DEBUGGING TAB */
      array(
        'key' => 'field_64c33143b6633',
        'label' => 'Debugging',
        'aria-label' => '',
        'type' => 'tab',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_64c3300c5bd47',
        'label' => 'Debugging',
        'name' => 'buildystrap_debug',
        'aria-label' => '',
        'type' => 'group',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_64c330335bd63',
            'label' => 'Enable Bugherd',
            'name' => 'enable_bugherd',
            'aria-label' => '',
            'type' => 'true_false',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(),
            'default_value' => 0,
            'ui' => 1,
          ),
          array(
            'key' => 'field_64c3304b5bd64',
            'label' => 'Bugherd API Key',
            'name' => 'bugherd_api_key',
            'aria-label' => '',
            'type' => 'text',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_64c330335bd63',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(),
          ),
        ),
      ),
      /* END DEBUGGING TAB */

    ],
    'location' => [
      [
        [
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'buildystrap-settings',
        ],
      ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'active' => true,
    'show_in_rest' => 0,
  ]);

endif;
