on:
  push:
    branches:
      - main
name: Deploy website when main is pushed
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.8.0
          run_install: false

      - name: Build Theme
        run: |
          pnpm install
          pnpm build

      - name: Build GUI
        working-directory: ./backend-editor/gui
        run: |
          pnpm install
          pnpm build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
